<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>Analisis</h3>

                <p>Tipos de Analisis</p>
            </div>
            <div class="icon">
                <i class="ion ion-erlenmeyer-flask"></i>
            </div>
            <a href="<?php echo BASE_URL. 'examenes';?>" class="small-box-footer">Ir a <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>Pacientes</h3>

                <p>Pacientes Catálogo</p>
            </div>
            <div class="icon">
                <i class="ion ion-ios-people"></i>
            </div>
            <a href="<?php echo BASE_URL. 'pacientes';?>" class="small-box-footer">Ir a <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>Usuarios</h3>

                <p>Usuarios y Configuraciones</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">Ir a <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>