<div class="lockscreen-wrapper">
    <div class="lockscreen-logo">
        <a href="<?php echo BASE_URL;?>"><b><?php echo APP_NAME?></b></a>
    </div>
    <!-- User name -->

    <!-- START LOCK SCREEN ITEM -->
    <div class="lockscreen-item">
        <!-- lockscreen image -->
        <div class="lockscreen-image">
            <img src="<?php echo $_layoutParams['ruta_img']?>Lock.png" alt="User Image">
        </div>
        <!-- /.lockscreen-image -->
        <!-- lockscreen credentials (contains the form) -->
        <form name="mfrmlogin" id="mfrmlogin" class="lockscreen-credentials" method="post" action="">
            <div class="input-group">
                <input type="hidden" name="enviar" value="1"/>
                <input type="password" class="form-control" placeholder="PIN" name="mPin" id="mPin" value="<?php if (isset($this->datos)) echo $this->datos['mPin']; ?>">

                <div class="input-group-btn">
                    <button type="button" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
                </div>
            </div>
        </form>
        <!-- /.lockscreen credentials -->
    </div>
    <!-- /.lockscreen-item -->
    <div class="help-block text-center">
        Use sus credenciales
    </div>
    <div class="lockscreen-footer text-center">
        Copyright © <?php echo date("Y"); ?> <b><a href="https://adminlte.io" class="text-black"><?php echo APP_COMPANY;?></a></b><br>
        All rights reserved
    </div>
</div>