<div class="error-page">

    <div class="error-content" style="margin-left: 20%;">

        <div class="image">
            <img src="<?php echo $_layoutParams['ruta_img']?>LogClin.png" alt="User Image">
        </div>
        <h2><i class="fa fa-warning text-red"></i> <?php if($this->mensaje) echo $this->mensaje;?></h2>
        <?php if(!Sessions::get('autenticado')):?>
            <a href="<?php echo BASE_URL. 'login';?>" class="btn btn-danger btn-flat"><i class="fa fa-user"></i>
                Iniciar Sesión</a>
        <?php endif;?>
    </div>
</div>
