<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?php echo $this->titulo;?></h3>

                <div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">

                    </div>
                </div>
            </div>
            <!-- /.box-header -->
                        <?php if(isset($this->pacientes)&& count($this->pacientes)):?>
                            <div class="box-body table-responsive no-padding">
                                <table id="tablemain" class="table table-bordered table-hover">
                                    <thead><tr>
                                        <th>Codigo</th>
                                        <th>PIN</th>
                                        <th>Nombres</th>
                                        <th>Apellido</th>
                                        <th>Identificacion</th>
                                        <th>Sexo</th>
                                        <th>Tipo</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php for($i=0;$i<count($this->pacientes);$i++):?>
                                    <tr>
                                        <td><?php echo $this->pacientes[$i]['id_cliente'];?></td>
                                        <td><?php echo $this->pacientes[$i]['pin'];?></td>
                                        <td><?php echo $this->pacientes[$i]['primer_nombre'];?></td>
                                        <td><?php echo $this->pacientes[$i]['segundo_nombre'];?></td>
                                        <td><?php echo $this->pacientes[$i]['dni'];?></td>
                                        <td><?php echo $this->pacientes[$i]['sexo'];?></td>
                                        <td><?php echo $this->pacientes[$i]['tipo'];?></td>
                                        <td><a class="btn btn-warning" href="<?php echo BASE_URL.'resultados/upload/'. $this->pacientes[$i]['id_cliente'];?>">Procesar</a> </td>
                                        <?php endfor;?>
                                    </thead></table>
                            </div>
                        <?php else:?>
                            <h5>No hay datos para mostrar.</h5>
                        <?php endif;?>
        </div>
        <!-- /.box -->
    </div>
</div>