<div class="col-md-6">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Datos Generales</h3>
        </div>
        <div class="box-body">
        <form id="frmAddRendimiento" class="form-horizontal" method="post"  action="<?php echo BASE_URL?>resultados/uploadfile" enctype="multipart/form-data">
                <input type="hidden"name="guardar" value="1"/>
                <div class="form-group">
                    <label>Titulo</label>
                    <input type="text" class="form-control" name="mTitulo" id="mTitulo" />
                </div>
                <div class="form-group">
                    <label >Archivo</label>
                    <input type="file" name="mArchivo"id="mArchivo"  />
                    <p>Tamaño máximo <?php echo  ini_get('upload_max_filesize');?></p>
                    <p style="color: red;"><?php echo $this->_error;?></p>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Ingresar Datos</button>
                    <button type="button" class="btn btn-warning">Cancelar</button>
                </div>
        </form>
        </div>
    </div>
</div>